### ISSUE TITLE
Add testing library 

### ISSUE THREAD

**Issue by benja2729** [benja2729/recursive-tracker#5]
**Investigation**

Learn about functional test approaches:
https://open-wc.org/testing/

**Tasks**

- [ ] Pull-in dependencies
- [ ] Set npm scripts
- [ ] Write tests for g-card
