### ISSUE TITLE
Github deployment path name-spacing

### ISSUE THREAD

**Issue by benja2729** [benja2729/recursive-tracker#6]
Github pages hosts this project from `/recursive-tracker`, but all urls in this app assume the origin `/`.

**Tasks**

- [ ] Add a way to find the path namespace from the current root
- [ ] Test to make sure all relevant urls use this namespace when importing or creating workers
- [ ] Make all other path references relative to avoid this issue in the future
